# Generated by Django 3.0.6 on 2021-01-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('size', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('addon', models.CharField(max_length=40)),
                ('instructions', models.CharField(max_length=100)),
            ],
        ),
    ]
