# Generated by Django 3.0.6 on 2021-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210105_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addon',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='instructions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
