# Generated by Django 3.0.6 on 2021-01-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210106_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='product',
            name='image_three',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='image_two',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('Made to Order', 'Made to Order'), ('1', '1'), ('2', '2'), ('3', '3')], default=('Made to Order', 'Made to Order'), max_length=55),
        ),
    ]
