# Generated by Django 3.0.6 on 2021-01-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210108_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
