# Generated by Django 3.0.6 on 2021-01-09 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210109_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.AlterField(
            model_name='product',
            name='addon',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Addon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
