# Generated by Django 3.0.6 on 2021-01-09 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Addon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
