# Generated by Django 3.0.6 on 2021-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210109_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addon_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='addon',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
