# Generated by Django 3.0.6 on 2021-02-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210208_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='addon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='addon_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.CharField(choices=[('Made to Order', 'Made to Order'), ('1', '1'), ('2', '2'), ('3', '3')], default=('Made to Order', 'Made to Order'), max_length=55, null=True),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=80, null=True)),
                ('price', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon', models.CharField(max_length=80, null=True)),
                ('price', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
