# Generated by Django 3.0.6 on 2021-02-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20210212_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.CharField(choices=[('No Limit', 'No Limit'), ('1', '1'), ('2', '2'), ('3', '3')], default=('No Limit', 'No Limit'), max_length=55, null=True),
        ),
    ]
