# Generated by Django 3.0.6 on 2021-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210212_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='price',
            new_name='price_addon',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='price',
            new_name='price_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
