# Generated by Django 3.0.6 on 2021-02-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20210212_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
