# Generated by Django 3.0.6 on 2021-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210226_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='week',
            field=models.CharField(default='Saturdays', max_length=55, null=True),
        ),
    ]
