# Generated by Django 3.0.6 on 2021-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_auto_20210227_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
