# Generated by Django 3.0.6 on 2021-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20210227_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price_addon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_size',
            field=models.FloatField(null=True),
        ),
    ]
