# Generated by Django 3.0.6 on 2021-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20210228_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='price_addon',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='price_size',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
