# Generated by Django 3.1.3 on 2021-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20210318_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instructions',
            field=models.CharField(blank=True, default='', max_length=125, null=True),
        ),
    ]
