# Generated by Django 3.1.7 on 2021-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20210318_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
