# Generated by Django 3.1.7 on 2021-03-31 06:32

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20210330_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.get_image_filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Image Name'),
        ),
    ]
