# Generated by Django 3.1.7 on 2021-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20210331_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_order_limit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
