# Generated by Django 3.1.7 on 2021-04-02 09:56

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_auto_20210401_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
