# Generated by Django 3.1.7 on 2021-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_auto_20210402_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/products/', verbose_name='Image'),
        ),
    ]
