# Generated by Django 3.0.6 on 2021-01-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], max_length=40, null=True)),
                ('payment_status', models.CharField(choices=[('To Receive', 'To Receive'), ('Processing', 'Processing'), ('Received', 'Received')], max_length=40, null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=255)),
            ],
        ),
    ]
