# Generated by Django 3.0.6 on 2021-01-10 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 5, 26, 48, 824614), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default=('Pending', 'Pending'), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('To Receive', 'To Receive'), ('Processing', 'Processing'), ('Received', 'Received')], default=('To Receive', 'To Receive'), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
