# Generated by Django 3.0.6 on 2021-01-10 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210111_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 5, 30, 59, 697548), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('To Receive', 'To Receive'), ('Processing', 'Processing'), ('Received', 'Received')], default='To Receive', max_length=40, null=True),
        ),
    ]
