# Generated by Django 3.0.6 on 2021-01-18 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210111_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 9, 37, 26, 582252), null=True),
        ),
    ]
