# Generated by Django 3.0.6 on 2021-01-18 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20210118_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 10, 55, 28, 314145), null=True),
        ),
    ]
