# Generated by Django 3.0.6 on 2021-02-10 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20210210_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 21, 25, 51, 502156), null=True),
        ),
    ]
