# Generated by Django 3.0.6 on 2021-02-11 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20210212_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 2, 16, 50, 845414), null=True),
        ),
    ]
