# Generated by Django 3.0.6 on 2021-02-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20210212_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 12, 30, 51, 846370), null=True),
        ),
    ]
