# Generated by Django 3.0.6 on 2021-02-25 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20210212_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 0, 11, 44, 324156), null=True),
        ),
    ]
