# Generated by Django 3.0.6 on 2021-02-25 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_auto_20210226_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 2, 15, 55, 351780), null=True),
        ),
    ]
