# Generated by Django 3.0.6 on 2021-02-27 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_auto_20210226_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 19, 27, 50, 342691), null=True),
        ),
    ]
