# Generated by Django 3.0.6 on 2021-02-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_auto_20210228_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
