# Generated by Django 3.0.6 on 2021-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210228_1926'),
        ('orders', '0057_auto_20210228_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='addons',
            field=models.ManyToManyField(blank=True, to='products.Addon'),
        ),
    ]
