# Generated by Django 3.0.6 on 2021-03-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_auto_20210305_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
