# Generated by Django 3.0.6 on 2021-03-06 02:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210306_0236'),
        ('orders', '0062_auto_20210306_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_information', to='orders.Order')),
                ('session_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_address', to='accounts.Address')),
                ('session_notifications', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_address', to='accounts.Notification')),
                ('session_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_address', to='accounts.BankAccount')),
                ('session_sender', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_information', to='accounts.CustomerInformation')),
            ],
        ),
    ]
