# Generated by Django 3.0.6 on 2021-03-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_orderinformation_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinformation',
            name='token_key',
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='token_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='token_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
