# Generated by Django 3.0.6 on 2021-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_auto_20210308_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='token_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
