# Generated by Django 3.1.7 on 2021-03-10 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20210228_1926'),
        ('orders', '0067_orderinformation_token_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size'),
        ),
    ]
