# Generated by Django 3.1.7 on 2021-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0068_auto_20210310_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinformation',
            name='token_id',
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='customer_jwt_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='customer_private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderinformation',
            name='customer_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
