# Generated by Django 3.0.6 on 2021-03-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0071_order_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device_id',
        ),
    ]
