# Generated by Django 3.1.3 on 2021-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0072_remove_order_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
