# Generated by Django 3.1.3 on 2021-03-18 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0074_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 22, 31, 7, 53371), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
