# Generated by Django 3.1.3 on 2021-03-18 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0075_auto_20210318_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 19, 22, 40, 0, 961416), null=True),
        ),
    ]
