# Generated by Django 3.1.7 on 2021-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0077_auto_20210318_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
