# Generated by Django 3.1.7 on 2021-04-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210404_0136'),
        ('orders', '0078_productorder_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='addons',
            field=models.ManyToManyField(blank=True, null=True, related_name='order_item_addons', to='products.Addon'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_order', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_size', to='products.size'),
        ),
    ]
