# Generated by Django 3.1.7 on 2021-04-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20210404_0136'),
        ('orders', '0079_auto_20210404_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='order_item_addons', to='products.Addon'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
