# Generated by Django 3.0.6 on 2021-04-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0080_auto_20210404_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_send',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
