# Generated by Django 3.0.6 on 2021-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0081_order_can_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='can_send',
        ),
    ]
