# Generated by Django 3.0.6 on 2021-01-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210120_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MERCHANT', 'Merchant'), ('CUSTOMER', 'Customer')], default='MERCHANT', max_length=50, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_information', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='merchantinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
