# Generated by Django 3.0.6 on 2021-02-08 14:23

import apps.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210120_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=155, null=True, verbose_name='address line1')),
                ('line2', models.CharField(max_length=155, null=True, verbose_name='address line2')),
                ('city', models.CharField(choices=[('Caloocan', 'Caloocan City'), ('Las Piñas', 'Las Piñas City'), ('Makati', 'Makati City'), ('Malabon', 'Malabon City'), ('Mandaluyong', 'Malanduyong City'), ('Manila', 'Manila City'), ('Marikina', 'Marikina City'), ('Muntinlupa', 'Muntinlupa City'), ('Navotas', 'Navotas City'), ('Parañaque', 'Parañaque City'), ('Pasay', 'Pasay City'), ('Pasig', 'Pasig City'), ('Pateros', 'Pateros City'), ('Quezon', 'Quezon City'), ('San Juan', 'San Juan City'), ('Taguig', 'Taguig City'), ('Valenzuela', 'Valenzuela City')], max_length=55, null=True, verbose_name='address city')),
                ('province', models.CharField(max_length=55, null=True, verbose_name='address province')),
                ('postal_code', models.CharField(max_length=4, null=True, validators=[apps.accounts.validators.only_int], verbose_name='address postal code')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('BPI', 'Bank of the Philippine Islands'), ('BDO', 'Banco de Oro'), ('GCash', 'GCash'), ('GrabPay', 'GrabPay')], max_length=55, null=True, verbose_name='bank name')),
                ('cardholder_name', models.CharField(choices=[('BPI', 'Bank of the Philippine Islands'), ('BDO', 'Banco de Oro'), ('GCash', 'GCash'), ('GrabPay', 'GrabPay')], max_length=155, null=True, verbose_name='cardholder name')),
                ('account_number', models.CharField(max_length=55, null=True, verbose_name='account number')),
                ('exp_date', models.CharField(max_length=4, null=True, validators=[apps.accounts.validators.exp_date], verbose_name='expiration date')),
                ('cvv', models.CharField(max_length=3, null=True, verbose_name='card verification value')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.BooleanField(default=False, null=True, verbose_name='sms notifications')),
                ('email', models.BooleanField(default=False, null=True, verbose_name='email notifications')),
            ],
        ),
        migrations.CreateModel(
            name='ShopInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=25, null=True, verbose_name='shop name')),
                ('shop_contact_number', models.CharField(max_length=15, null=True, verbose_name='contact number')),
                ('shop_username', models.CharField(max_length=55, null=True, verbose_name='shop username')),
                ('shop_cod', models.BooleanField(default=False, null=True, verbose_name='shop cash on delivery')),
                ('shop_account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_account', to='accounts.BankAccount')),
                ('shop_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_address', to='accounts.Address')),
                ('shop_days_open', models.ManyToManyField(to='accounts.Days')),
            ],
        ),
        migrations.CreateModel(
            name='ShopLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=255, null=True, verbose_name='instagram link')),
                ('facebook', models.CharField(max_length=255, null=True, verbose_name='facebook link')),
                ('twitter', models.CharField(max_length=255, null=True, verbose_name='twitter link')),
            ],
        ),
        migrations.RenameField(
            model_name='customerinformation',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='instagram_name',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='customer_mobile_number',
            field=models.CharField(max_length=15, null=True, validators=[apps.accounts.validators.only_int], verbose_name='mobile number'),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MERCHANT', 'Merchant'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=50, null=True, verbose_name='role'),
        ),
        migrations.DeleteModel(
            name='MerchantInformation',
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='shop_links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_links', to='accounts.SocialMediaLinks'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='shop_logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_logo', to='accounts.ShopLogo'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='customer_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_address', to='accounts.Address'),
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='customer_links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='accounts.SocialMediaLinks'),
        ),
        migrations.AddField(
            model_name='customerinformation',
            name='customer_notifications',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifs', to='accounts.Notifications'),
        ),
    ]
