# Generated by Django 3.0.6 on 2021-02-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210208_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='customer_username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='customer username'),
        ),
        migrations.AddField(
            model_name='days',
            name='toggle',
            field=models.BooleanField(default=False, null=True, verbose_name='shop cash on delivery'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('NCR/MM', 'Metro Manila')], max_length=55, null=True, verbose_name='address province'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_shop', to='accounts.BankAccount'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_shop', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_shop', to='accounts.SocialMediaLinks'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_shop', to='accounts.ShopLogo'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='shop username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email is already being used by another account.'}, max_length=150, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='shop username'),
        ),
    ]
