# Generated by Django 3.0.6 on 2021-02-10 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210209_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits, and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
