# Generated by Django 3.0.6 on 2021-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210210_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[('Bank of the Philippine Islands', 'BPI'), ('Banco de Oro', 'BDO'), ('GCash', 'GCash'), ('GrabPay', 'GrabPay')], max_length=55, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cardholder_name',
            field=models.CharField(choices=[('Bank of the Philippine Islands', 'BPI'), ('Banco de Oro', 'BDO'), ('GCash', 'GCash'), ('GrabPay', 'GrabPay')], max_length=155, null=True, verbose_name='cardholder name'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='day_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='from_hour',
            field=models.PositiveSmallIntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')]),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='to_hour',
            field=models.PositiveSmallIntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')]),
        ),
    ]
