# Generated by Django 3.0.6 on 2021-02-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210210_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Caloocan City', 'Caloocan'), ('Las Piñas City', 'Las Piñas'), ('Makati City', 'Makati'), ('Malabon City', 'Malabon'), ('Malanduyong City', 'Malanduyong'), ('Manila City', 'Manila'), ('Marikina City', 'Marikina'), ('Muntinlupa City', 'Muntinlupa'), ('Navotas City', 'Navotas'), ('Parañaque City', 'Parañaque'), ('Pasay City', 'Pasay'), ('Pasig City', 'Pasig'), ('Pateros City', 'Pateros'), ('Quezon City', 'Quezon City'), ('San Juan City', 'San Juan'), ('Taguig City', 'Taguig'), ('Valenzuela City', 'Valenzuela')], default=None, max_length=55, null=True, verbose_name='address city'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(choices=[('Metro Manila', 'Metro Manila')], default=None, max_length=55, null=True, verbose_name='address province'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[('Bank of the Philippine Islands', 'BPI'), ('Banco de Oro', 'BDO'), ('Gcash', 'GCash'), ('GrabPay', 'GrabPay')], max_length=55, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='cardholder_name',
            field=models.CharField(max_length=155, null=True, verbose_name='cardholder name'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='day_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='day_to',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='from_hour',
            field=models.PositiveSmallIntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='to_hour',
            field=models.PositiveSmallIntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')], default=None, null=True),
        ),
    ]
