# Generated by Django 3.0.6 on 2021-02-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210210_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openhours',
            name='from_hour',
            field=models.PositiveSmallIntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM'), (24, '12:00 PM')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='to_hour',
            field=models.PositiveSmallIntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM'), (24, '12:00 PM')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_shop', to='accounts.BankAccount'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_shop', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_delivery_schedule',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.OpenHours'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_shop', to='accounts.SocialMediaLinks'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_shop', to='accounts.ShopLogo'),
        ),
    ]
