# Generated by Django 3.0.6 on 2021-02-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210210_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_account',
        ),
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_delivery_schedule',
        ),
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_links',
        ),
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_logo',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openhours',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ShopInformation'),
        ),
        migrations.AddField(
            model_name='shoplogo',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_shop', to='accounts.ShopInformation'),
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
