# Generated by Django 3.0.6 on 2021-02-11 17:54

import apps.accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210210_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinformation',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='customer_links',
        ),
        migrations.RemoveField(
            model_name='customerinformation',
            name='customer_notifications',
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='exp_date',
            field=models.CharField(max_length=5, null=True, validators=[apps.accounts.validators.exp_date], verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoplogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
