# Generated by Django 3.0.6 on 2021-03-06 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210212_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinformation',
            name='customer_email',
            field=models.EmailField(max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='address line2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ShopInformation'),
        ),
        migrations.AlterField(
            model_name='shoplogo',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_shop', to='accounts.ShopInformation'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
