# Generated by Django 3.1.7 on 2021-03-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210319_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (4, 'Wednesday'), (8, 'Thursday'), (16, 'Friday'), (32, 'Saturday'), (64, 'Sunday')])),
                ('everyday', models.BooleanField(default=False, null=True, verbose_name='everyday delivery')),
            ],
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_name',
            field=models.CharField(max_length=30, null=True, verbose_name='shop name'),
        ),
    ]
