# Generated by Django 3.1.7 on 2021-03-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210320_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_cod',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='shop cash on delivery'),
        ),
        migrations.AlterField(
            model_name='shoplogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/shop_logos'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='facebook',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='instagram',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='instagram link'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='twitter',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='twitter link'),
        ),
    ]
