# Generated by Django 3.1.7 on 2021-03-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210320_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(choices=[('', 'Choose bank / e-wallet'), ('BPI', 'Bank of the Philippine Islands (BPI)'), ('BDO', 'Banco de Oro (BDO)'), ('UB', 'UnionBank PH'), ('GCash', 'GCash PH'), ('PayMaya', 'PayMaya PH'), ('GrabPay', 'GrabPay')], max_length=55, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='shoplogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/shop_logos'),
        ),
    ]
