# Generated by Django 3.1.7 on 2021-03-24 11:31

import apps.accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210322_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDeliverySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_options', models.PositiveIntegerField(choices=[(1, 'I book the courier'), (2, 'Buyer books courier'), (4, 'Buyer picks up from location')])),
                ('line1', models.CharField(default='', max_length=155, null=True, verbose_name='delivery line1')),
                ('line2', models.CharField(blank=True, default='', max_length=155, null=True, verbose_name='delivery line2')),
                ('city', models.CharField(choices=[('Caloocan City', 'Caloocan'), ('Las Piñas City', 'Las Piñas'), ('Makati City', 'Makati'), ('Malabon City', 'Malabon'), ('Malanduyong City', 'Malanduyong'), ('Manila City', 'Manila'), ('Marikina City', 'Marikina'), ('Muntinlupa City', 'Muntinlupa'), ('Navotas City', 'Navotas'), ('Parañaque City', 'Parañaque'), ('Pasay City', 'Pasay'), ('Pasig City', 'Pasig'), ('Pateros City', 'Pateros'), ('Quezon City', 'Quezon City'), ('San Juan City', 'San Juan'), ('Taguig City', 'Taguig'), ('Valenzuela City', 'Valenzuela')], default=None, max_length=55, null=True, verbose_name='delivery city')),
                ('province', models.CharField(choices=[('Metro Manila', 'Metro Manila')], default=None, max_length=55, null=True, verbose_name='delivery province')),
                ('postal_code', models.CharField(default='', max_length=4, null=True, validators=[apps.accounts.validators.only_int], verbose_name='delivery postal code')),
            ],
        ),
        migrations.CreateModel(
            name='ShopGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_cod', models.BooleanField(blank=True, default=False, null=True, verbose_name='shop cash on delivery')),
                ('cutoff_days', models.IntegerField(default=0, null=True)),
                ('cutoff_time', models.CharField(max_length=10, null=True)),
                ('delivery_days', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (4, 'Wednesday'), (8, 'Thursday'), (16, 'Friday'), (32, 'Saturday'), (64, 'Sunday')])),
                ('delivery_everyday', models.BooleanField(default=False, null=True, verbose_name='everyday delivery')),
                ('delivery_from_hour', models.PositiveSmallIntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM'), (24, '12:00 PM')], default=None, null=True)),
                ('delivery_to_hour', models.PositiveSmallIntegerField(choices=[(0, '12:00 AM'), (1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM'), (24, '12:00 PM')], default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopinformation',
            name='shop_cod',
        ),
        migrations.DeleteModel(
            name='DeliveryDays',
        ),
        migrations.AddField(
            model_name='shopgeneralsettings',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_general_settings', to='accounts.shopinformation'),
        ),
        migrations.AddField(
            model_name='shopdeliverysettings',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_delivery_settings', to='accounts.shopinformation'),
        ),
    ]
