# Generated by Django 3.1.7 on 2021-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210324_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdeliverysettings',
            name='delivery_options',
        ),
        migrations.AddField(
            model_name='shopdeliverysettings',
            name='buyer_books',
            field=models.BooleanField(default=False, null=True, verbose_name='buyer books'),
        ),
        migrations.AddField(
            model_name='shopdeliverysettings',
            name='buyer_picks_up',
            field=models.BooleanField(default=False, null=True, verbose_name='buyer picks up'),
        ),
        migrations.AddField(
            model_name='shopdeliverysettings',
            name='seller_books',
            field=models.BooleanField(default=False, null=True, verbose_name='seller books'),
        ),
        migrations.AddField(
            model_name='shopinformation',
            name='shop_delivery_fees',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
