# Generated by Django 3.1.7 on 2021-03-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210324_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='shop_email',
            field=models.EmailField(help_text='Your customers will contact you through this email address.', max_length=150, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_hours_shop', to='accounts.shopinformation'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_delivery_settings', to='accounts.shopinformation'),
        ),
        migrations.AlterField(
            model_name='shopgeneralsettings',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_general_settings', to='accounts.shopinformation'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='This will be used for your order form link (quicklink.ph/username).', max_length=150, null=True, unique=True, verbose_name='shop username'),
        ),
        migrations.AlterField(
            model_name='shoplogo',
            name='shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_shop', to='accounts.shopinformation'),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email is already being used by another account.'}, help_text='Please use a business email address.', max_length=150, null=True, unique=True, verbose_name='email address'),
        ),
    ]
