# Generated by Django 3.1.7 on 2021-03-25 12:57

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210325_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='buyer_books',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='buyer books'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='buyer_picks_up',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='buyer picks up'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='city',
            field=models.CharField(blank=True, choices=[('Caloocan City', 'Caloocan'), ('Las Piñas City', 'Las Piñas'), ('Makati City', 'Makati'), ('Malabon City', 'Malabon'), ('Malanduyong City', 'Malanduyong'), ('Manila City', 'Manila'), ('Marikina City', 'Marikina'), ('Muntinlupa City', 'Muntinlupa'), ('Navotas City', 'Navotas'), ('Parañaque City', 'Parañaque'), ('Pasay City', 'Pasay'), ('Pasig City', 'Pasig'), ('Pateros City', 'Pateros'), ('Quezon City', 'Quezon City'), ('San Juan City', 'San Juan'), ('Taguig City', 'Taguig'), ('Valenzuela City', 'Valenzuela')], default=('Caloocan City', 'Caloocan'), max_length=55, null=True, verbose_name='delivery city'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='line1',
            field=models.CharField(blank=True, default='Address Line 1', max_length=155, null=True, verbose_name='delivery line1'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='line2',
            field=models.CharField(blank=True, default='Address Line 2', max_length=155, null=True, verbose_name='delivery line2'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='postal_code',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True, validators=[apps.accounts.validators.only_int], verbose_name='delivery postal code'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='province',
            field=models.CharField(blank=True, choices=[('Metro Manila', 'Metro Manila')], default=('Metro Manila', 'Metro Manila'), max_length=55, null=True, verbose_name='delivery province'),
        ),
        migrations.AlterField(
            model_name='shopdeliverysettings',
            name='seller_books',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='seller books'),
        ),
        migrations.AlterField(
            model_name='shopinformation',
            name='shop_delivery_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
