# Generated by Django 3.1.7 on 2021-03-29 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('orders', '0077_auto_20210318_2240'),
        ('accounts', '0035_auto_20210327_0139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='CustomerNotification',
        ),
        migrations.CreateModel(
            name='MerchantNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_payouts', models.BooleanField(default=True, null=True)),
                ('daily_order_summary', models.BooleanField(default=True, null=True)),
                ('product_updates', models.BooleanField(default=True, null=True)),
                ('marketing_updates', models.BooleanField(default=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True, verbose_name='Merchant Feedback Sender')),
                ('email', models.EmailField(max_length=55, null=True, verbose_name='Merchant Feedback Email')),
                ('shop_name', models.CharField(max_length=55, null=True, verbose_name='Merchant Feedback Shop')),
                ('feedback', models.CharField(max_length=255, null=True, verbose_name='Merchant Feedback')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
