# Generated by Django 3.0.6 on 2021-04-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210329_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='can_send_updates',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
