# Generated by Django 3.0.6 on 2021-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_shopinformation_can_send_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinformation',
            name='shop_slug',
            field=models.SlugField(null=True),
        ),
    ]
