# Generated by Django 3.0.6 on 2021-02-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expected', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_received', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
                ('total_receivables', models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True)),
            ],
        ),
    ]
